# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/PP.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/bcd_to_7seg.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/cla_adder.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/cla_adder_8bit.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/cla_gen.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/clk_gen.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/debounce2.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/half_adder.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/half_adder_4.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/led_mux.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/param_D_reg.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/two_stage_multiplier.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/xor_gate.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/xor_gate_4.v}
  {C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/sources_1/new/top_level_module.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/constrs_1/new/constraint_TSM.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/theal/Documents/SCHOOL/CMPE 125 Lab/GitLabs/lab5/Lab5.srcs/constrs_1/new/constraint_TSM.xdc}}]


synth_design -top fpga_two_stage_mult -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_two_stage_mult.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_two_stage_mult_utilization_synth.rpt -pb fpga_two_stage_mult_utilization_synth.pb"
